;BEGIN FRAGMENT CODE - Do not edit anything between this and the end comment
Scriptname Fragments:Quests:QF_VAW_GlobalVariables_01000C92 Extends Quest Hidden Const

;BEGIN FRAGMENT Fragment_Stage_0000_Item_00
Function Fragment_Stage_0000_Item_00()
;BEGIN CODE
FoodMag_Value_RestoreHealth_Convenience_01_Small.SetValue(50.0)
FoodMag_Value_RestoreHealth_Convenience_02_Medium.SetValue(150.0)
FoodMag_Value_RestoreHealth_Convenience_03_Large.SetValue(300.0)

FoodMag_Value_RestoreHealth_HighEnd_01_VerySmall.SetValue(50.0)
FoodMag_Value_RestoreHealth_HighEnd_02_Small.SetValue(150.0)
FoodMag_Value_RestoreHealth_HighEnd_02_SmallMedium.SetValue(200.0)
FoodMag_Value_RestoreHealth_HighEnd_03_Medium.SetValue(300.0)
FoodMag_Value_RestoreHealth_HighEnd_04_Large.SetValue(400.0)
FoodMag_Value_RestoreHealth_HighEnd_05_XLarge.SetValue(500.0)
FoodMag_Value_RestoreHealth_HighEnd_06_Huge.SetValue(600.0)
FoodMag_Value_RestoreHealth_HighEnd_07_XHuge.SetValue(750.0)

FoodMag_Value_RestoreHealth_Raw_01_Small.SetValue(50.0)
FoodMag_Value_RestoreHealth_Raw_02_Medium.SetValue(100.0)
;END CODE
EndFunction
;END FRAGMENT

;END FRAGMENT CODE - Do not edit anything between this and the begin comment

GlobalVariable Property FoodMag_Value_RestoreHealth_Convenience_01_Small Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_Convenience_02_Medium Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_Convenience_03_Large Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_01_VerySmall Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_02_Small Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_02_SmallMedium Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_03_Medium Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_04_Large Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_05_XLarge Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_06_Huge Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_HighEnd_07_XHuge Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_Raw_01_Small Auto Const

GlobalVariable Property FoodMag_Value_RestoreHealth_Raw_02_Medium Auto Const
